#!/bin/bash

mkdir -p kernel_out
cp -f ./arch/arm/configs/bcm21664_hawaii_ss_kyleve_rev00_defconfig ./kernel_out/.config
make -j8 ARCH=arm KBUILD_OUTPUT=./kernel_out oldnoconfig
make -j8 ARCH=arm KBUILD_OUTPUT=./kernel_out
cp -f ./kernel_out/arch/arm/boot/zImage ./arch/arm/boot/
cp -rf ./kernel_out/arch/arm/boot/compressed/vmlinux ./arch/arm/boot/compressed/
cp -rf ./kernel_out/vmlinux ./
mkdir tmp
cd tmp
cp -f ../arch/arm/boot/zImage ./zImage
cp ../arch/arm/tools/boot.img-ramdisk.cpio.gz ./boot.img-ramdisk.cpio.gz
cp ../arch/arm/tools/mkbootimg ./mkbootimg
cp ../arch/arm/tools/META-INF_kyleve.zip ./META-INF.zip
./mkbootimg --kernel zImage --ramdisk boot.img-ramdisk.cpio.gz --board kyleve --pagesize 4096 --base 0x82000000 -o boot.img
unzip META-INF.zip
zip -r tmp META-INF boot.img
mv -f tmp.zip ../flash.zip
mv -f boot.img ../boot.img
cd ../
rm -rf tmp
